services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  rabbit:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  vrisc.service:
    build: ./VRisc
    restart: always
    ports:
      - "6002:8080"
    depends_on:
      - mongo
      - rabbit
      - compiler.service

  compiler.service:
    build: ./Compiler
    restart: always
    ports:
      - "6003:8080"
    depends_on:
      - redis
      - rabbit
